### ISSUE TITLE
Support the director and table

### ISSUE THREAD

**Issue by tkuchiki** [KeisukeYamashita/go-vcl#2]
## What

Same as a title

## Why

`director` and `table` are not defined as follows:
https://github.com/KeisukeYamashita/go-vcl/blob/master/internal/token/token.go#L59-L70

Would you please consider supporting the `director` and  `table`?

Thanks

### refs

- https://docs.fastly.com/vcl/directors/
- https://docs.fastly.com/vcl/table/

**Comment by KeisukeYamashita** [comment]
@tkuchiki  Thank you for your report. I didn't know fastly VCL has that.
I will like to work on this. Thank you.

**Comment by KeisukeYamashita** [comment]
## Todo

### Directory block

- [x] Add directory block
    - #4 
- [ ] Add percentage type

### Table block 

- [ ] Add table block
- [ ] Add hash object

**Comment by KeisukeYamashita** [comment]
@tkuchiki Thank you for reporting. Now, it is supported.
